### ISSUE TITLE
Server won't load properly now

### ISSUE THREAD

**Issue by sjdodge123** [TrueOsiris/docker-vrising#38]
Server ran fine on Wednesday and Thursday of this week. I stopped the container safely Thurs night and tried to boot it up tonight (Sunday) and I keep getting a connection timeout.

Ports are open, didn't change the config. Server stdout shows some 429 http error. I'll post a stack shortly. Is anyone else having issues suddenly?

**Comment by geoffmca** [comment]
From Discord:
So for those interesting in the Docker containers breaking as well: it is the same issue as the Windows servers have (described earlier in regards to the lib_burst_generated.dll because of the avx requirement). That being said, the solution would be to deploy your own Docker and remember that there is no official support for Docker (or Linux in general) and I am in no way 100% sure as to how and why it crashes -- but below is what worked for me and I am willing to run the risk it breaks again soon.

So, like the Windows server, Wine in the Docker containers I used (e.g. TrueOsiris) also breaks because of the lack of AVX support. I spun up a docker container by myself and before launching wine VRisingServer.exe -persistentDatapath..., you can add a check to see if your/virtualized CPU supports it (e.g. grep -o 'avx[^ ]*' /proc/cpuinfo) and if not, you can simply rename the file using the mv command (mv ${f} ${f}.bak), where $f is the .dll.

I forked the TrueOsiris project on Github and you can see those changes in start.sh (https://github.com/baldandbearded93/docker-vrising-noavx/blob/main/start.sh). I have added a Pull Request for this change, so if they still maintain it and accept, it should help the unofficial docker users here. 

You could also consider https://hub.docker.com/r/baldandbearded93/vrising-server as a docker container for now (it should work out of the box with the TrueOsiris one), but full credit and all should go them, and the moment the TrueOsiris container updates or an official hotfix/update comes around, I'll remove this one 

Keep in mind loading the server may take up to 5 minutes (you can check your persistentpath/VRisingServer.log to see if it actually crashed or not) (edited)

So for those interesting in the Docker containers breaking as well: it is the same issue as the Windows servers have (described earlier in regards to the lib_burst_generated.dll because of the avx requirement). That being said, the solution would be to deploy your own Docker and remember that there is no official support for Docker (or Linux in general) and I am in no way 100% sure as to how and why it crashes -- but below is what worked for me and I am willing to run the risk it breaks again soon. So, like the Windows server, Wine in the Docker containers I used (e.g. TrueOsiris) also breaks because of the lack of AVX support. I spun up a docker container by myself and before launching wine VRisingServer.exe -persistentDatapath..., you can add a check to see if your/virtualized CPU supports it (e.g. grep -o 'avx[^ ]*' /proc/cpuinfo) and if not, you can simply rename the file using the mv command (mv ${f} ${f}.bak), where $f is the .dll. I forked the TrueOsiris project on Github and you can see those changes in start.sh (https://github.com/baldandbearded93/docker-vrising-noavx/blob/main/start.sh). I have added a Pull Request for this change, so if they still maintain it and accept, it should help the unofficial docker users here.  You could also consider https://hub.docker.com/r/baldandbearded93/vrising-server as a docker container for now (it should work out of the box with the TrueOsiris one), but full credit and all should go them, and the moment the TrueOsiris container updates or an official hotfix/update comes around, I'll remove this one  Keep in mind loading the server may take up to 5 minutes (you can check your persistentpath/VRisingServer.log to see if it actually crashed or not) (edited)

**Comment by nickktoast** [comment]
> Server ran fine on Wednesday and Thursday of this week. I stopped the container safely Thurs night and tried to boot it up tonight (Sunday) and I keep getting a connection timeout.
> 
> Ports are open, didn't change the config. Server stdout shows some 429 http error. I'll post a stack shortly. Is anyone else having issues suddenly?

How are you restarting the server? Are you running ‘docker compose up’ or are you doing something else?

**Comment by sjdodge123** [comment]
> > Server ran fine on Wednesday and Thursday of this week. I stopped the container safely Thurs night and tried to boot it up tonight (Sunday) and I keep getting a connection timeout.
> > 
> > Ports are open, didn't change the config. Server stdout shows some 429 http error. I'll post a stack shortly. Is anyone else having issues suddenly?
> 
> How are you restarting the server? Are you running ‘docker compose up’ or are you doing something else? 


So usually I'm using the docker-compose  -f config.yml up to create my server. Once I have it defined I use start and stop

**Comment by geoffmca** [comment]
Look at the pending PR, that fixes the issue (I remoted into my docker image and updated manually)

**Comment by TrueOsiris** [comment]
@geoffmca Can you confirm that this is fixed with the latest merge from baldandbearded93, or should I have a deeper look into your explanation?
